#ifndef SWTI_SERIALIZE_VERSION_H
#define SWTI_SERIALIZE_VERSION_H

    #define SWTI_SERIALIZE_VERSION_MAJOR (0)
    #define SWTI_SERIALIZE_VERSION_MINOR (1)
    #define SWTI_SERIALIZE_VERSION_PATCH (8)

#endif
