#ifndef SWTI_SERIALIZE_VERSION_H
#define SWTI_SERIALIZE_VERSION_H

    #define SWTI_SERIALIZE_VERSION_MAJOR (0)
    #define SWTI_SERIALIZE_VERSION_MINOR (2)
    #define SWTI_SERIALIZE_VERSION_PATCH (0)

#endif
